version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/public
permissions:
  - object: /var/www/public/index.html
    owner: root
    group: root
    mode: 644
    type:
      - file
